"""BKYS başlangıç veritabanı şeması."""

from alembic import op

revision = "a98502dae8b4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE TYPE cihaz_durumu AS ENUM ('Kullanima_Hazir', 'Rezerve', 'Kullanimda', 'Arizali', 'Bakimda', 'Kalibrasyonda', 'Kullanim_Disi');")
    op.execute("CREATE TYPE ogrenci_turu AS ENUM (\n    'GONULLU',\n    'DANISMA_MASASI'\n);")
    op.execute("CREATE TYPE denetim_olay_turu AS ENUM (\n    'LOGIN',\n    'LOGIN_FAILED',\n    'CREATE',\n    'UPDATE',\n    'CANCEL',\n    'ROLE_CHANGE',\n    'DEVICE_STATUS_CHANGE'\n);")
    op.execute('CREATE TABLE bolumler (\n    bolum_id SERIAL PRIMARY KEY,\n    bolum_adi VARCHAR(150) UNIQUE NOT NULL, \n    sorumlu_ad_soyad VARCHAR(100) NOT NULL, \n    iletisim_bilgisi VARCHAR(100), \n    aktif_mi BOOLEAN DEFAULT TRUE\n);')
    op.execute("CREATE TABLE danisan_kodlari (\n    danisan_kod_id VARCHAR(50) PRIMARY KEY, \n    ucretli_mi BOOLEAN NOT NULL DEFAULT TRUE, \n    istisna_turu VARCHAR(50) DEFAULT 'YOK',   \n    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,\n    olusturulma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP\n);")
    op.execute('CREATE TABLE odalar (\n    oda_id SERIAL PRIMARY KEY,\n    oda_adi VARCHAR(50) UNIQUE NOT NULL,\n    kapasite INT DEFAULT 1, \n    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE\n);')
    op.execute('CREATE TABLE roller (\n    rol_id SERIAL PRIMARY KEY,\n    rol_adi VARCHAR(50) UNIQUE NOT NULL\n);')
    op.execute('CREATE TABLE izinler (\n    izin_id SERIAL PRIMARY KEY,\n    izin_adi VARCHAR(100) UNIQUE NOT NULL,\n    aciklama VARCHAR(255)\n);')
    op.execute('CREATE TABLE rol_izinleri (\n    rol_id INT NOT NULL\n        REFERENCES roller(rol_id),\n\n    izin_id INT NOT NULL\n        REFERENCES izinler(izin_id),\n\n    izin_var SMALLINT NOT NULL\n        DEFAULT 0,\n\n    PRIMARY KEY (rol_id, izin_id),\n\n    CHECK (izin_var IN (0, 1))\n);')
    op.execute('CREATE TABLE kullanicilar (\n    kullanici_id SERIAL PRIMARY KEY,\n\n    kullanici_adi VARCHAR(100) UNIQUE NOT NULL,\n\n    parola_hash VARCHAR(255) NOT NULL,\n\n    rol_id INT NOT NULL\n        REFERENCES roller(rol_id),\n\n    \n    \n    aktif_mi BOOLEAN NOT NULL\n        DEFAULT TRUE,\n    \n    \n    basarisiz_giris_sayisi INT NOT NULL\n        DEFAULT 0,\n\n    \n    \n    kilit_bitis_zamani TIMESTAMP NULL,\n\n    olusturulma_tarihi TIMESTAMP NOT NULL\n        DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute('CREATE TABLE personel (\n    personel_id SERIAL PRIMARY KEY,\n\n    kullanici_id INT UNIQUE NOT NULL\n        REFERENCES kullanicilar(kullanici_id),\n\n    personel_kodu VARCHAR(50) UNIQUE NOT NULL,\n\n    aktif_mi BOOLEAN NOT NULL\n        DEFAULT TRUE,\n\n    olusturulma_tarihi TIMESTAMP NOT NULL\n        DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute('CREATE TABLE ogrenciler (\n    ogrenci_id SERIAL PRIMARY KEY,\n\n    kullanici_id INT UNIQUE\n        REFERENCES kullanicilar(kullanici_id),\n\n    ad_soyad VARCHAR(100) NOT NULL,\n\n    ogrenci_numarasi VARCHAR(50) UNIQUE NOT NULL,\n\n    telefon VARCHAR(20),\n\n    tur ogrenci_turu NOT NULL,\n\n    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE,\n\n    olusturulma_tarihi TIMESTAMP NOT NULL\n        DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute('CREATE TABLE danisma_masasi_oturumlari (\n    oturum_id SERIAL PRIMARY KEY,\n\n    ogrenci_id INT NOT NULL\n        REFERENCES ogrenciler(ogrenci_id),\n\n    baslangic_zamani TIMESTAMP NOT NULL\n        DEFAULT CURRENT_TIMESTAMP,\n\n    bitis_zamani TIMESTAMP,\n\n    onaylandi_mi BOOLEAN NOT NULL DEFAULT FALSE,\n\n    CHECK (\n        bitis_zamani IS NULL\n        OR bitis_zamani > baslangic_zamani\n    )\n);')
    op.execute('CREATE TABLE faaliyetler (\n    faaliyet_id SERIAL PRIMARY KEY,\n\n    faaliyet_adi VARCHAR(100) UNIQUE NOT NULL,\n\n    puan INT NOT NULL\n        CHECK (puan >= 0),\n\n    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE\n);')
    op.execute('CREATE TABLE faaliyet_birimleri (\n    birim_id SERIAL PRIMARY KEY,\n\n    birim_adi VARCHAR(50) UNIQUE NOT NULL,\n\n    aktif_mi BOOLEAN NOT NULL DEFAULT TRUE\n);')
    op.execute('CREATE TABLE ogrenci_faaliyet_takip (\n    takip_id SERIAL PRIMARY KEY,\n\n    ogrenci_id INT NOT NULL\n        REFERENCES ogrenciler(ogrenci_id),\n\n    faaliyet_id INT NOT NULL\n        REFERENCES faaliyetler(faaliyet_id),\n\n    adet INT NOT NULL\n        CHECK (adet > 0),\n\n    birim_id INT NOT NULL\n        REFERENCES faaliyet_birimleri(birim_id),\n\n    faaliyet_tarihi DATE NOT NULL\n        DEFAULT CURRENT_DATE,\n\n    aciklama VARCHAR(255),\n\n    onaylandi_mi BOOLEAN NOT NULL\n        DEFAULT FALSE,\n\n    olusturulma_tarihi TIMESTAMP NOT NULL\n        DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute('CREATE TABLE denetim_kayitlari (\n    denetim_id BIGSERIAL PRIMARY KEY,\n\n    \n    \n    kullanici_id INT\n        REFERENCES kullanicilar(kullanici_id),\n\n    olay_turu denetim_olay_turu NOT NULL,\n\n    \n    hedef_tablo VARCHAR(100),\n\n    \n    hedef_kayit_id INT,\n\n    olusturulma_tarihi TIMESTAMP NOT NULL\n        DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute("CREATE TABLE cihazlar (\n    cihaz_id SERIAL PRIMARY KEY,\n    envanter_kodu VARCHAR(50) UNIQUE NOT NULL,\n    cihaz_adi VARCHAR(100) NOT NULL,\n    marka_model VARCHAR(100),\n    seri_no VARCHAR(100) UNIQUE,\n    zimmetli_oda_id INT REFERENCES odalar(oda_id), \n    durum cihaz_durumu DEFAULT 'Kullanima_Hazir',\n    kayit_tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);")
    op.execute('CREATE TABLE cihaz_rezervasyonlari (\n    rezervasyon_id SERIAL PRIMARY KEY,\n    cihaz_id INT REFERENCES cihazlar(cihaz_id),\n    bolum_id INT REFERENCES bolumler(bolum_id), \n    rezervasyonu_yapan_personel_id INT REFERENCES personel(personel_id), \n    baslangic_zamani TIMESTAMP NOT NULL,\n    bitis_zamani TIMESTAMP NOT NULL,\n    iptal_edildi_mi BOOLEAN DEFAULT FALSE, \n    kullanilacak_oda_id INT REFERENCES odalar(oda_id),\n    proje_turu VARCHAR(50), \n    proje_adi_aciklamasi VARCHAR(255) \n);')
    op.execute('CREATE TABLE cihaz_arizalari (\n    ariza_id SERIAL PRIMARY KEY,\n    cihaz_id INT REFERENCES cihazlar(cihaz_id),\n    bildiren_personel VARCHAR(100),\n    ariza_aciklamasi TEXT NOT NULL,\n    bildirim_tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n    cozum_tarihi TIMESTAMP,\n    cozuldu_mu BOOLEAN DEFAULT FALSE\n);')
    op.execute('CREATE TABLE cihaz_bakimlari (\n    bakim_id SERIAL PRIMARY KEY,\n    cihaz_id INT REFERENCES cihazlar(cihaz_id),\n    bakim_yapan_kisi VARCHAR(100),\n    yapilan_islem TEXT,\n    maliyet DECIMAL(10, 2),\n    bakim_tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute('CREATE TABLE cihaz_kalibrasyonlari (\n    kalibrasyon_id SERIAL PRIMARY KEY,\n    cihaz_id INT REFERENCES cihazlar(cihaz_id),\n    kalibrasyon_yapan_kurum VARCHAR(100),\n    gecerlilik_tarihi DATE,\n    sertifika_no VARCHAR(100),\n    islem_tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute('CREATE TABLE cihaz_bakim_planlari (\n    plan_id SERIAL PRIMARY KEY,\n    cihaz_id INT REFERENCES cihazlar(cihaz_id),\n    gorev_turu VARCHAR(100) NOT NULL, \n    periyot_gun INT NOT NULL, \n    uyari_suresi_gun INT DEFAULT 1, \n    sonraki_gorev_tarihi DATE NOT NULL, \n    aktif_mi BOOLEAN DEFAULT TRUE\n);')
    op.execute('CREATE TABLE cihaz_takip_parametreleri (\n    parametre_id SERIAL PRIMARY KEY,\n    cihaz_id INT REFERENCES cihazlar(cihaz_id),\n    parametre_adi VARCHAR(100) NOT NULL, \n    parametre_degeri VARCHAR(100) NOT NULL, \n    birim VARCHAR(50), \n    son_guncelleme TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);')
    op.execute("CREATE TABLE randevular (\n    randevu_id SERIAL PRIMARY KEY,\n    danisan_kod_id VARCHAR(50) NOT NULL REFERENCES danisan_kodlari(danisan_kod_id),\n    psikolog_id INT NOT NULL REFERENCES personel(personel_id),\n    oda_id INT NOT NULL REFERENCES odalar(oda_id),\n    baslangic_zamani TIMESTAMP NOT NULL,\n    bitis_zamani TIMESTAMP NOT NULL,\n    durum VARCHAR(30) DEFAULT 'PLANLANDI',\n    olusturulma_tarihi TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP\n);")
    op.execute('CREATE TABLE oda_etkinlikleri (\n    etkinlik_id SERIAL PRIMARY KEY,\n    oda_id INT NOT NULL REFERENCES odalar(oda_id),\n    organize_eden_personel_id INT NOT NULL REFERENCES personel(personel_id), \n    etkinlik_adi VARCHAR(150) NOT NULL, \n    katilimci_sayisi INT, \n    baslangic_zamani TIMESTAMP NOT NULL,\n    bitis_zamani TIMESTAMP NOT NULL,\n    iptal_edildi_mi BOOLEAN DEFAULT FALSE\n);')
    op.execute("INSERT INTO roller (rol_adi) VALUES\n    ('PSIKOLOG'),\n    ('MEMUR'),\n    ('MUDUR'),\n    ('DANISMA_OGRENCISI'),\n    ('PROJE_ASISTANI'),\n    ('ADMIN');")
    op.execute("INSERT INTO faaliyetler (faaliyet_adi, puan) VALUES\n    ('Yüz Yüze Anket', 5),\n    ('Online Anket', 1),\n    ('İç Tanıtım Görüşmesi', 3),\n    ('Dış Tanıtım Görüşmesi', 10),\n    ('Sponsorluk', 20),\n    ('Sempozyum', 10),\n    ('PsiLab Etkinliği', 3);")
    op.execute("INSERT INTO faaliyet_birimleri (birim_adi) VALUES\n    ('KISI'),\n    ('SAAT');")
    op.execute("INSERT INTO izinler (izin_adi, aciklama) VALUES\n    ('RANDEVU_OLUSTUR', 'Randevu oluşturma'),\n    ('RANDEVU_DUZENLE', 'Randevu düzenleme'),\n    ('RANDEVU_IPTAL', 'Randevu iptal etme'),\n    ('TAKVIM_GORUNTULE', 'Randevu takvimini görüntüleme'),\n    ('ODA_DURUMU_GORUNTULE', 'Oda kullanım durumunu görüntüleme'),\n    ('CIHAZ_UYGUNLUK_GORUNTULE', 'Cihaz uygunluğunu görüntüleme'),\n    ('CIHAZ_ENVANTER_YONET', 'Cihaz envanterini yönetme'),\n    ('CIHAZ_REZERVASYON', 'Cihaz rezervasyonu yapma'),\n    ('BAKIM_KAYITLARI_YONET', 'Bakım kayıtlarını yönetme'),\n    ('KALIBRASYON_KAYITLARI_YONET', 'Kalibrasyon kayıtlarını yönetme'),\n    ('ARIZA_KAYITLARI_YONET', 'Arıza kayıtlarını yönetme'),\n    ('KULLANICI_OLUSTUR', 'Kullanıcı oluşturma'),\n    ('PERSONEL_TANIMLA', 'Personel tanımlama'),\n    ('KULLANICI_PASIFLESTIR', 'Kullanıcı pasifleştirme'),\n    ('ROL_ATAMA_DEGISTIRME', 'Rol atama veya değiştirme'),\n    ('AUDIT_KAYITLARI_INCELE', 'Audit kayıtlarını inceleme'),\n    ('DANISMA_OTURUMU_YONET', 'Danışma masası oturumunu yönetme'),\n    ('CIHAZ_EKLE', 'Sisteme yeni cihaz ekleme'),\n    ('FAALIYET_KAYITLARI_DUZENLE', 'Faaliyet kayıtlarını düzenleme'),\n    ('CIHAZ_TAKIP_KONTROL_LISTESI', 'Cihaz takip kontrol listesini yönetme'),\n    ('IZIN_TANIMLA', 'Sisteme yeni izin tanımlama'),\n    ('IZIN_DUZENLE', 'Mevcut izin tanımını düzenleme'),\n    ('ROL_IZIN_YONET', 'Rollerin izinlerini yönetme'),\n    ('ROL_OLUSTUR', 'Sisteme yeni rol oluşturma'),\n    ('ROL_DUZENLE', 'Mevcut rolü düzenleme'),\n    ('FAALIYET_BIRIMI_DUZENLE', 'Faaliyet birimlerini yönetme');")
    op.execute("INSERT INTO rol_izinleri (rol_id, izin_id, izin_var)\nSELECT\n    r.rol_id,\n    i.izin_id,\n    CASE WHEN i.izin_adi IN (\n        'RANDEVU_OLUSTUR',\n        'RANDEVU_DUZENLE',\n        'RANDEVU_IPTAL',\n        'TAKVIM_GORUNTULE',\n        'ODA_DURUMU_GORUNTULE',\n        'CIHAZ_UYGUNLUK_GORUNTULE'\n    ) THEN 1 ELSE 0 END\nFROM roller r\nCROSS JOIN izinler i\nWHERE r.rol_adi = 'PSIKOLOG';")
    op.execute("INSERT INTO rol_izinleri (rol_id, izin_id, izin_var)\nSELECT\n    r.rol_id,\n    i.izin_id,\n    CASE WHEN i.izin_adi IN (\n        'TAKVIM_GORUNTULE',\n        'ODA_DURUMU_GORUNTULE',\n        'CIHAZ_UYGUNLUK_GORUNTULE',\n        'CIHAZ_ENVANTER_YONET',\n        'CIHAZ_REZERVASYON',\n        'BAKIM_KAYITLARI_YONET',\n        'KALIBRASYON_KAYITLARI_YONET',\n        'ARIZA_KAYITLARI_YONET',\n        'DANISMA_OTURUMU_YONET',\n        'CIHAZ_EKLE',\n        'FAALIYET_KAYITLARI_DUZENLE',\n        'CIHAZ_TAKIP_KONTROL_LISTESI'\n    ) THEN 1 ELSE 0 END\nFROM roller r\nCROSS JOIN izinler i\nWHERE r.rol_adi = 'MEMUR';")
    op.execute("INSERT INTO rol_izinleri (rol_id, izin_id, izin_var)\nSELECT\n    r.rol_id,\n    i.izin_id,\n    CASE WHEN i.izin_adi IN (\n        'TAKVIM_GORUNTULE',\n        'ODA_DURUMU_GORUNTULE',\n        'CIHAZ_UYGUNLUK_GORUNTULE',\n        'CIHAZ_ENVANTER_YONET',\n        'BAKIM_KAYITLARI_YONET',\n        'KALIBRASYON_KAYITLARI_YONET',\n        'ARIZA_KAYITLARI_YONET',\n        'KULLANICI_OLUSTUR',\n        'PERSONEL_TANIMLA',\n        'KULLANICI_PASIFLESTIR',\n        'ROL_ATAMA_DEGISTIRME',\n        'AUDIT_KAYITLARI_INCELE',\n        'DANISMA_OTURUMU_YONET',\n        'CIHAZ_EKLE',\n        'FAALIYET_KAYITLARI_DUZENLE',\n        'CIHAZ_TAKIP_KONTROL_LISTESI'\n    ) THEN 1 ELSE 0 END\nFROM roller r\nCROSS JOIN izinler i\nWHERE r.rol_adi = 'MUDUR';")
    op.execute("INSERT INTO rol_izinleri (rol_id, izin_id, izin_var)\nSELECT\n    r.rol_id,\n    i.izin_id,\n    CASE WHEN i.izin_adi IN (\n        'RANDEVU_OLUSTUR',\n        'RANDEVU_DUZENLE',\n        'RANDEVU_IPTAL',\n        'TAKVIM_GORUNTULE',\n        'ODA_DURUMU_GORUNTULE',\n        'DANISMA_OTURUMU_YONET'\n    ) THEN 1 ELSE 0 END\nFROM roller r\nCROSS JOIN izinler i\nWHERE r.rol_adi = 'DANISMA_OGRENCISI';")
    op.execute("INSERT INTO rol_izinleri (rol_id, izin_id, izin_var)\nSELECT\n    r.rol_id,\n    i.izin_id,\n    CASE WHEN i.izin_adi IN (\n        'TAKVIM_GORUNTULE',\n        'ODA_DURUMU_GORUNTULE',\n        'CIHAZ_UYGUNLUK_GORUNTULE',\n        'CIHAZ_REZERVASYON',\n        'FAALIYET_KAYITLARI_DUZENLE'\n    ) THEN 1 ELSE 0 END\nFROM roller r\nCROSS JOIN izinler i\nWHERE r.rol_adi = 'PROJE_ASISTANI';")
    op.execute("INSERT INTO rol_izinleri (rol_id, izin_id, izin_var)\nSELECT\n    r.rol_id,\n    i.izin_id,\n    1\nFROM roller r\nCROSS JOIN izinler i\nWHERE r.rol_adi = 'ADMIN';")


def downgrade() -> None:
    raise NotImplementedError(
        "Başlangıç şemasını otomatik silmek veri kaybına neden olabilir."
    )
